version: '3.7'

services:
  web:
    build: .
    ports:
      - "60082：80"
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:7.0
    pull_policy: missing
    restart: always
